### ISSUE TITLE
jikanAPI的v3版本已弃用，脚本无法正常运行

### ISSUE THREAD

**Issue by squanbo** [KimigaiiWuyi/Bangumi_Auto_Rename#17]
直接使用python脚本执行重命名，报错如下：
`剧集名称: 摇曳露营△TV版
【SNAME】: Specials
【SEASON】【TMDB未搜索到】转为MyAnimeList搜索！

Traceback (most recent call last):
  File "/opt/tools/Bangumi_Auto_Rename.py", line 952, in <module>
    process_task_path(INPUT_PATH, {})
  File "/opt/tools/Bangumi_Auto_Rename.py", line 846, in process_task_path
    process_path(path, R)
  File "/opt/tools/Bangumi_Auto_Rename.py", line 678, in process_path
    search_result = jikan.search(
  File "/usr/local/lib/python3.9/dist-packages/jikanpy/jikan.py", line 242, in search
    return self._request(url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/jikanpy/jikan.py", line 84, in _request
    return self._wrap_response(response, url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/jikanpy/jikan.py", line 78, in _wrap_response
    raise APIException(response.status_code, json_response, **kwargs)

jikanpy.exceptions.APIException: HTTP 410 - status=410, type=BadResponseException, message=v3 has been discontinued. For more information visit https://bit.ly/jikan-v3-deprecation, upgrade=Please upgrade to v4: https://docs.api.jikan.moe/ for search type=anime, query=Yuru Camp`

**Comment by KimigaiiWuyi** [comment]
安装了错误的依赖
请执行`pip uninstall jikanpy`卸载依赖
执行`pip install jikanpy-v4>=1.0.2` 安装依赖
一定要先卸载再安装
